version: '2.1'
services:
    one:
        build:
            context: .
        image: hc-test
        environment:
            MAX: "-1"
        healthcheck:
            test: /healthcheck
            interval: 10s
        command: /run_tail
    two:
        image: hc-test
        healthcheck:
            test: /healthcheck
            interval: 10s
        environment:
            MAX: "0"
        depends_on:
            one:
                condition: service_healthy
        command: /run_tail
    three:
        image: hc-test
        depends_on:
            two:
                condition: service_healthy
        command: /run_date
            
            
